name: Deploy multi-container-fibo
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t liran86/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true liran86/react-test npm test
 
      - run: docker build -t liran86/multi-container-fibo-client ./client
      - run: docker build -t liran86/multi-container-fibo-nginx ./nginx
      - run: docker build -t liran86/multi-container-fibo-server ./server
      - run: docker build -t liran86/multi-container-fibo-worker ./worker
 
      - run: docker push liran86/multi-container-fibo-client
      - run: docker push liran86/multi-container-fibo-nginx
      - run: docker push liran86/multi-container-fibo-server
      - run: docker push liran86/multi-container-fibo-worker
 
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-container-fibo
          environment_name: multi-container-fibo-env
          existing_bucket_name: elasticbeanstalk-us-east-1-923445559289
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip